#      ___           ___           ___
#     /\  \         /\  \         /\  \
#    /::\  \       |::\  \        \:\  \       ___
#   /:/\:\  \      |:|:\  \        \:\  \     /\__\
#  /:/  \:\  \   __|:|\:\  \   _____\:\  \   /:/__/
# /:/__/ \:\__\ /::::|_\:\__\ /::::::::\__\ /::\  \
# \:\  \ /:/  / \:\~~\  \/__/ \:\~~\~~\/__/ \/\:\  \__
#  \:\  /:/  /   \:\  \        \:\  \        ~~\:\/\__\
#   \:\/:/  /     \:\  \        \:\  \          \::/  /
#    \::/  /       \:\__\        \:\__\         /:/  /
#     \/__/         \/__/         \/__/         \/__/
#
# OMNI: A Hybrid Granular and Spatial Processing Environment
# =========================================================
# CONFIG YOUR HEART OUT
# =========================================================





# ======= I/O

input_channels: 1
output_channels: 2


# ======= Spatial
useSpatial: true
spatial:
#    type: loudspeaker
    type: binaural
    num_processors: 2
    
    
    
# ======= Granulation
granular:
    num_voices: 8

