#      ___           ___           ___
#     /\  \         /\  \         /\  \
#    /::\  \       |::\  \        \:\  \       ___
#   /:/\:\  \      |:|:\  \        \:\  \     /\__\
#  /:/  \:\  \   __|:|\:\  \   _____\:\  \   /:/__/
# /:/__/ \:\__\ /::::|_\:\__\ /::::::::\__\ /::\  \
# \:\  \ /:/  / \:\~~\  \/__/ \:\~~\~~\/__/ \/\:\  \__
#  \:\  /:/  /   \:\  \        \:\  \        ~~\:\/\__\
#   \:\/:/  /     \:\  \        \:\  \          \::/  /
#    \::/  /       \:\__\        \:\__\         /:/  /
#     \/__/         \/__/         \/__/         \/__/
#
# OMNI: A Hybrid Granular and Spatial Processing Environment
# =========================================================
# CONFIG YOUR HEART OUT
# =========================================================



# ======= I/O

input_channels: 1
output_channels: 2
sample_rate: 44100
buffer_size: 512


# ======= Spatial
useSpatial: true
spatial:
    type: binaural
#    type: binaural            
    num_processors: 2
    proc1_mapping: [0,1,2,3]
    proc2_mapping: [4,5,6,7]
    
    
    
# ======= Granulation
granular:
    num_voices: 8


# ======= Graphics
graphics:
    renderSpatializer: true
    bufferRenderType: "2D"
    background_color: [0,0,0,255]
